# Generated by Django 2.2.5 on 2019-09-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190925_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='employee_password',
            field=models.CharField(max_length=1000),
        ),
    ]
