# Generated by Django 2.2.5 on 2019-09-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20190926_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='employee_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
